// ARIA snapshots: the accessibility tree of each view, as YAML.
//
// This is the regression half of the accessibility work. The structural
// properties -- roles, accessible names, heading levels, table headers, how
// label/value pairs nest -- are exactly what a screen reader consumes, and
// exactly what a CSS refactor can quietly destroy. The .kv blocks in this site
// were once a grid of anonymous divs that looked right and read as unrelated
// runs of text; in a tree snapshot that is a visible diff rather than an
// invisible defect.
//
// Snapshots are external files, generated by `npm run a11y:update` and reviewed
// like any other diff. They are NOT hand-written: a hand-written expectation
// records what someone believed the tree was.
const { test, expect } = require("@playwright/test");
const { VIEWS, showView, showFirstProductDetail } = require("./views");

test.beforeEach(async ({ page }) => {
  await page.goto("/index.html");
});

for (const name of Object.keys(VIEWS)) {
  test(`${name} view accessibility tree`, async ({ page }) => {
    const view = await showView(page, name);
    await expect(page.locator(view.panel)).toMatchAriaSnapshot({
      name: `view-${name}.aria.yml`,
    });
  });
}

test("product detail accessibility tree", async ({ page }) => {
  await showFirstProductDetail(page);
  await expect(page.locator("#detail-view")).toMatchAriaSnapshot({
    name: "detail.aria.yml",
  });
});

test("the dependency graph's table equivalent", async ({ page }) => {
  // The table exists because the diagram is unusable non-visually, so its tree
  // is the one that has to carry the whole meaning -- caption, column headers,
  // row headers.
  await showView(page, "graph");
  await page.click("#graphTable");
  await expect(page.locator("#graph-view")).toMatchAriaSnapshot({
    name: "graph-table.aria.yml",
  });
});

test("sidebar filters", async ({ page }) => {
  // Named <aside aria-label="Filters">, and ~40 controls deep on every view.
  // Its tree is what decides whether that is navigable or a wall.
  await expect(page.locator("aside")).toMatchAriaSnapshot({
    name: "sidebar.aria.yml",
  });
});

test("landmarks and the skip link are the first things present", async ({ page }) => {
  // Asserted directly rather than by snapshot: these are the entry points, and a
  // snapshot diff would let them vanish silently under an accepted update.
  await expect(page.locator("a.skip-link")).toHaveAttribute("href", "#main-content");
  await expect(page.locator("main#main-content")).toBeAttached();
  await expect(page.locator("aside[aria-label]")).toBeAttached();
  await expect(page.locator("header")).toBeAttached();
  await expect(page.locator('[role="status"][aria-live]')).toBeAttached();

  // The skip link must be reachable first, not merely present.
  await page.keyboard.press("Tab");
  await expect(page.locator("a.skip-link")).toBeFocused();
});
